# Generated by Django 5.0.2 on 2024-04-12 01:29

import api_development.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0004_date_alter_image_description_image_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api_development.date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=api_development.models.user_directory_path),
        ),
    ]
