# Generated by Django 5.0.2 on 2024-05-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0006_alter_image_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_ref',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
