# Generated by Django 5.0.2 on 2024-05-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0007_machine_image_image_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_development.machine'),
        ),
    ]
