# Generated by Django 5.0.2 on 2024-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0008_image_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
