# Generated by Django 5.0.2 on 2024-05-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0009_segmentation_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='api_development.image'),
        ),
    ]
