# Generated by Django 5.0.2 on 2024-05-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0010_alter_segmentation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentation',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='segmentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_development.segmentation'),
        ),
    ]
