# Generated by Django 5.0.2 on 2024-05-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0011_remove_segmentation_image_image_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='related_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api_development.machine'),
        ),
        migrations.AlterField(
            model_name='image',
            name='segmentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api_development.segmentation'),
        ),
    ]
