# Generated by Django 5.0.2 on 2024-05-07 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0012_machine_related_directory_alter_image_machine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecheck',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='imagecheck',
            name='proposed_corrections',
        ),
        migrations.AddField(
            model_name='imagecheck',
            name='affected_segments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecheck',
            name='target_classType',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_checks', to=settings.AUTH_USER_MODEL)),
                ('proposed_corrections', models.ManyToManyField(related_name='corrections', to='api_development.imagecheck')),
            ],
            options={
                'verbose_name': 'Correction',
                'verbose_name_plural': 'Corrections',
            },
        ),
    ]
