# Generated by Django 5.0.2 on 2024-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0013_remove_imagecheck_checked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecheck',
            name='check_date',
        ),
        migrations.AddField(
            model_name='correction',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
