# Generated by Django 5.0.2 on 2024-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0014_remove_imagecheck_check_date_correction_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True),
        ),
    ]
