# Generated by Django 5.0.2 on 2024-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0015_alter_correction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='proposed_corrections',
            field=models.ManyToManyField(blank=True, null=True, related_name='corrections', to='api_development.imagecheck'),
        ),
    ]
