# Generated by Django 5.0.2 on 2024-05-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0017_alter_imagecheck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecheck',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api_development.image'),
        ),
    ]
