# Generated by Django 5.0.2 on 2024-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0019_machine_last_scanned_machine_valid_file_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='proposed_corrections',
            field=models.ManyToManyField(related_name='corrections', to='api_development.imagecheck'),
        ),
    ]
