# Generated by Django 5.0.2 on 2024-05-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0020_alter_correction_proposed_corrections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
    ]
