# Generated by Django 5.0.2 on 2024-05-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0021_remove_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='segmentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_development.segmentation'),
        ),
    ]
