# Generated by Django 5.0.2 on 2024-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0023_imagecheck_confirmed_alter_correction_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
