# Generated by Django 5.0.2 on 2024-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0025_remove_metric_accuracy_remove_metric_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_class_mismatches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_false_negatives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_false_positives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_true_positives',
            field=models.IntegerField(default=0),
        ),
    ]
